# Usar la última imagen base de Ubuntu
FROM ubuntu:latest

# Actualizar el manejador de paquetes APT
RUN apt-get update

# Actualizar el software instalado
RUN apt-get upgrade -y

# Definir el comando por defecto al ejecutar un contenedor de esta imagen
CMD ["echo", "Hello, World!"]
